export const paths = {
  root: "/",
  login: "/login",
  dashboard: "/dashboard",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminRoles: "/admin/roles",
  adminDocumentTypes: "/admin/document-types",
  adminApprovalRoutes: "/admin/approval-routes",
  adminActivityLogs: "/admin/activity-logs",
  requester: "/requester",
  requesterRequests: "/requester/requests",
  requesterCreateRequest: "/requester/requests/new",
  requesterActivityHistory: "/requester/activity-history",
  approver: "/approver",
  approverPending: "/approver/pending",
  approverReviewed: "/approver/reviewed",
  unauthorized: "/unauthorized",
  notFound: "*",
} as const;
